name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Discord Commits
      uses: Sniddl/discord-commits@v1.3
      with:
        webhook: fZyXG25Z00L_ZMrcEpgJyhWfxMJe4w_qLHwR0HQ7c2uSW2NmfOJz5Y64-oMM8OuFJHmx
        message: "Start Build"

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
